services:
  grafana:
    user: root
    container_name: "wasilak-datadog-datasource"

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.3.0}
        development: true
        anonymous_auth_enabled: true
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/wasilak-datadog-datasource
      - .:/root/wasilak-datadog-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.wasilak-datadog-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: wasilak-datadog-datasource
